encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),

    # Al escribir algo en la dirección url, se envía lo escrito a views con el nombre "name"  
      
    path("wiki/<str:name>", views.buscar, name="buscar"),

    # Recibe los datos escritos en la form "buscar"
    path("recibir", views.recibir, name="recibir"),

    # Crear nueva página
    path("crear", views.crear, name="crear"),

    # Editar página existente
    path("editar", views.editar, name="editar"),

    # Ir a página aleatoria
    path("aleatoria", views.aleatoria, name="aleatoria"),

    # Vamos a crear un path para una aplicacion de prueba
    path("prueba", views.prueba, name="prueba"),

    path("formulario", views.formulario, name="formulario")    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),    
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from multiprocessing.sharedctypes import Value
from django import forms

# En este archivo definimos todos los formularios a ser utilizados en views.py

# Definimos un form de donde recibiremos la cadena que busca el usuario
class BuscarForm(forms.Form):
    busqueda = forms.CharField(label="Buscar")

# Esta form sirve para ingresar una nueva entrada o editar una existente
class AgregarEntradaForm(forms.Form):  
    titulo = forms.CharField(label="Título")  
    contenido = forms.CharField(label="Contenido", widget=forms.Textarea)
    tipo = forms.CharField(label='Tipo', widget=forms.HiddenInput, initial="Agregar")

# Esta form sirve para editar una entrada existente
class Editar(forms.Form):
    contenido = forms.CharField(widget=forms.Textarea)

encyclopedia/views.py
from multiprocessing import context
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

import random

from . import markdown2
from . import util, forms 

# Definimos las funciones a usar

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


# Esta función recibe el nombre de una entrada y devuelve una página con la entrada (Si existe)
def buscar(request, name):    
    entrada = markdown2.markdown(util.get_entry(name))
    #entrada = util.get_entry(name)
    edit = 1                                                        # Esta bandera habilita el botón de edición
    contexto = {"name":name, "entrada":entrada, "edit":edit}
    if entrada != None:
        return render(request, "encyclopedia/layout.html", contexto) 
    else:
        return render(request, "encyclopedia/error.html", contexto)          

    

# Esta función recibe el nombre de una entrada en la barra de búsqueda y devuelve la página con la entrada

def recibir(request):    
    if request.method == 'GET':
        datos = request.GET.get('q')              #Recibimos los datos de la form y guardamos aquí        
        entrada = util.get_entry(datos)
        coincidencias = []                        # Creamos una lista vacía. Llenaremos con coincidencias
        context = {'entries': coincidencias,'datos': datos, }  #Diccionario para que entienda nuestro template
        if entrada != None:            
            return buscar(request, datos)           # Gracias, Django, por permitirme hacer esto            
        else:
            lista = util.list_entries()                             # Guardamos las entradas en una lista            
            i = 0
            while i < len(lista):
                x = -1
                x = lista[i].find(datos)
                if x == -1:
                    coincidencias = coincidencias
                else:
                    coincidencias.append(lista[i])                    
                i += 1
            return render(request, "encyclopedia/talvezquiso.html", context)
    else:
        return render(request, "encyclopedia/error2.html")   

# Función que crea nuevas entradas
def crear(request):
    entrada = forms.AgregarEntradaForm                      # Creamos el form    
    context = {'form':entrada,}                             # Creamos el contexto     
    if request.method == 'POST':                            # Si el método es un POST
        entrada = forms.AgregarEntradaForm(request.POST)    # Llenamos los datos en el form   
        if entrada.is_valid():                              # Validamos los datos
            datosentrada = entrada.cleaned_data
            context.update(datosentrada)
            if util.get_entry(datosentrada["titulo"]) == None:
                util.save_entry(datosentrada["titulo"],datosentrada["contenido"])
                #return render(request, "encyclopedia/layout.html", context)
                return buscar(request, datosentrada["titulo"])
            elif datosentrada["tipo"]=="Editar":
                util.save_entry(datosentrada["titulo"],datosentrada["contenido"])                
                return buscar(request, datosentrada["titulo"])
            else:
                return render(request, "encyclopedia/yaexiste.html", context)                                        
        else:            
            return render(request, "encyclopedia/error.html")            
        return render(request, "encyclopedia/crear.html", context)
    else:
        return render(request, "encyclopedia/crear.html", context)  


# Aplicación para editar entradas
def editar(request):    
    datos = "Vacío"
    entrada = "Todavía no hay nada"
    if request.method == 'GET':                                   
        datos = request.GET.get('entrada')                        # Recibimos los datos del get
        entrada = util.get_entry(datos)                           # Guardamos en entrada
    editarform = forms.AgregarEntradaForm(initial={'titulo':datos, 'contenido':entrada, "tipo":"Editar"})    
    context = {'datos':datos, 'entrada':entrada, 'form':editarform}
    return render(request, "encyclopedia/editar.html", context)

def aleatoria(request):
    lista = util.list_entries()                               # Creamos una lista con los nombres de las entradas
    datos = random.choice(lista)                             # Elegimos un elemento aleatorio
    return buscar(request, datos)                             # Ya listo      

def prueba(request):  
    if request.method == 'GET':     # Los datos se reciben. Ahora es necesario almacenarlos en una variable
        datos = request.GET.get('q')
        return render(request, "encyclopedia/prueba.html" )
    else:
        return render(request, "encyclopedia/error2.html")

def formulario(request):     
    return render(request, "encyclopedia/formulario.html" )
        

encyclopedia/templates/encyclopedia/crear.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Crear nueva entrada</title>        
    </head>
    <body>
        <h1>Crear nueva entrada</h1>
        <form action="{% url 'encyclopedia:crear' %}" method="post">
        <!--form action="crear" method="post"-->
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
        </form>
    </body>
</html>

encyclopedia/templates/encyclopedia/editar.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Editar entrada</title>
    </head>
    <body>
        <h1>Editar entrada</h1>   
        <form action="{% url 'encyclopedia:crear' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
        </form>
    </body>
</html>

encyclopedia/templates/encyclopedia/error.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Error</title>
    </head>
    <body>
        <h1>Ha ocurrido un error</h1>
        <h2>Este es el primer tipo de error que puede ocurrir</h2>
        <h3>Se entra a este error por la funcion "encyclopedia:buscar"</h3>
        <h4>El valor de la variable es {{datos}} </h4>
    </body>
</html>

encyclopedia/templates/encyclopedia/error2.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Error</title>
    </head>
    <body>
        <h1>Ha ocurrido un error</h1>
        <h2>Este es el segundo tipo de error que puede ocurrir</h2>
        <h3>Se entra a este error por medio de la funcion "encyclopedia:recibir" </h3>
    </body>
</html>

encyclopedia/templates/encyclopedia/formulario.html
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Formulario de prueba</title>
</head>    
<body>
    <form action="prueba" method="get">
    <input class="search" type="text" name="q" id="datosprueba" placeholder="Buscar aquí">
    </form>
</body>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}">{{ entry }}</a>  </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{{name}}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:recibir' %}" method="get">
                <!--form action="recibir" method="get"-->
                    <!--{{form}}-->
                    <input class="search" type="text" name="q"  id="recibirdatos" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:crear' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:aleatoria' %}">Random Page</a>    
                </div>
                <div>
                    {% if edit == 1 %}
                    <!--a href="{% url 'encyclopedia:editar' %}"> Edit Page </a-->
                    <form action="{% url 'encyclopedia:editar' %}">
                        <input type="hidden" id="entrada" name="entrada" value={{name}}>
                        <input type="submit" value="Editar">
                    </form>
                    {% endif %}
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {{entrada|safe}}   <!-- Se le pone el filtro "safe" para evitar el escaping-->
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/prueba.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Prueba</title>        
    </head>
    <body>
        <h1>Esta es una página de prueba</h1>
        <h2>Escribimos la palabra {{datos}}</h2>
    </body>
</html>

encyclopedia/templates/encyclopedia/talvezquiso.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Tal vez quiso...</title>        
    </head>
    <body>
        <h1>La palabra "{{datos}}" no  arrojó resultados</h1>
        <h2>Tal vez quiso decir:</h2>
        <ul>
            {% for entry in entries %}
                <li><a href="wiki/{{entry}}">{{ entry }}</a>  </li>
            {% endfor %}
        </ul>
    </body>
</html>

encyclopedia/templates/encyclopedia/yaexiste.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Ya existe</title>
    </head>
    <body>
        <h1>La entrada que intenta crear ya existe</h1>
        <h2> El titulo de la entrada es {{titulo}} </h2>
        <h4>Vuelva al <a href="{% url 'encyclopedia:index' %}"> Inicio </a></h4>
    </body>
</html>